# Generated by Django 4.0.6 on 2022-08-08 12:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Biographic')),
                ('date_of_birth', models.DateField(default=datetime.date.today, verbose_name='Date of birth')),
                ('phone', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator('\\d{11}', 'Minimum 11', code='invalid')], verbose_name='Phone')),
                ('balance', models.IntegerField(default=0)),
                ('person_disc', models.IntegerField(default=0)),
            ],
        ),
    ]
