# Generated by Django 4.0.6 on 2022-08-23 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0017_delete_purchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('CART', 'In cart'), ('AWAITING_ARRIVAL', 'Awaiting_arrival'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('PAID', 'Paid'), ('AWAITING_DELIVERY', 'Awaiting delivery'), ('SENT', 'Sent'), ('FINISHED', 'Finished')], default='CART', max_length=50)),
                ('warranty_days', models.IntegerField(default=30, verbose_name='Dates of warranty')),
                ('orders_time', models.DateTimeField(blank=True, null=True, verbose_name='Orders date time field')),
                ('city', models.CharField(default='12345', max_length=100, verbose_name='Delivery city')),
                ('address', models.CharField(default='12345', max_length=250, verbose_name='Delivery address')),
                ('orders_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='ID of order')),
                ('total_orders_price', models.IntegerField(blank=True, null=True, verbose_name='Total price of order')),
                ('item', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.item')),
                ('user', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
