# Generated by Django 4.0.6 on 2022-08-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_purchase_orders_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='orders_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ID of order'),
        ),
    ]
