# Generated by Django 4.0.6 on 2022-08-08 12:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.IntegerField(default=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('content_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=50)),
                ('tag_description', models.CharField(max_length=100)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.item')),
                ('author', models.CharField(max_length=100)),
                ('date_of_release', models.DateField(default=datetime.date.today, verbose_name='Date of release')),
            ],
            bases=('goods.item',),
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.item')),
                ('manufacturer', models.CharField(max_length=50)),
            ],
            bases=('goods.item',),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(verbose_name='State of item')),
                ('rented_from', models.DateField(default=datetime.date.today, verbose_name='Rented from')),
                ('rented_to', models.DateField(default=datetime.date.today, verbose_name='Rented to')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(verbose_name='State of item')),
                ('warranty', models.IntegerField(default=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(to='goods.tag', verbose_name='tags'),
        ),
    ]
