# Generated by Django 4.0.6 on 2022-08-10 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.item'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='state',
            field=models.IntegerField(default=0, verbose_name='State of item'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='item',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.item'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='state',
            field=models.IntegerField(default=0, verbose_name='State of item'),
        ),
    ]
