# Generated by Django 4.0.6 on 2022-08-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_purchase_user_rent_user_alter_purchase_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Amount of ordered items'),
        ),
        migrations.AddField(
            model_name='rent',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Amount of ordered items'),
        ),
    ]
