# Generated by Django 4.0.6 on 2022-08-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_purchase_amount_rent_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='warranty',
        ),
        migrations.RemoveField(
            model_name='rent',
            name='amount',
        ),
        migrations.AddField(
            model_name='purchase',
            name='warranty_days',
            field=models.IntegerField(default=30, verbose_name='Dates of warranty'),
        ),
    ]
