# Generated by Django 4.0.6 on 2022-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_purchase_amount_remove_purchase_warranty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='discounted_price',
            field=models.IntegerField(default=0, verbose_name='Price with discount'),
        ),
    ]
