# Generated by Django 4.0.6 on 2022-08-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('goods', '0006_remove_purchase_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='discounted_price',
            field=models.IntegerField(default=0, verbose_name='Price with discount'),
        ),
        migrations.AlterField(
            model_name='item',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
