# Generated by Django 4.0.6 on 2022-08-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_purchase_discounted_price_alter_item_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='discounted_price',
        ),
    ]
