# Generated by Django 4.0.6 on 2022-08-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_purchase_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='discounted_price',
        ),
    ]
