# Generated by Django 4.0.6 on 2022-08-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_remove_purchase_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='orders_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Orders date time field'),
        ),
    ]
