# Generated by Django 4.0.6 on 2022-08-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_purchase_orders_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.CharField(default='12345', max_length=250, verbose_name='Delivery address'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='city',
            field=models.CharField(default='12345', max_length=100, verbose_name='Delivery city'),
        ),
    ]
