# Generated by Django 4.0.6 on 2022-08-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_purchase_address_purchase_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tag',
            new_name='tags',
        ),
    ]
