# Generated by Django 4.0.6 on 2022-08-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_rename_tag_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='state',
            field=models.CharField(choices=[('CART', 'In cart'), ('AWAITING_ARRIVAL', 'Awaiting_arrival'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('PAID', 'Paid'), ('AWAITING_DELIVERY', 'Awaiting delivery'), ('SENT', 'Sent'), ('FINISHED', 'Finished')], default='CART', max_length=50),
        ),
        migrations.AlterField(
            model_name='rent',
            name='state',
            field=models.CharField(choices=[('CART', 'In cart'), ('AWAITING_ARRIVAL', 'Awaiting_arrival'), ('AWAITING_PAYMENT', 'Awaiting payment'), ('PAID', 'Paid'), ('AWAITING_DELIVERY', 'Awaiting delivery'), ('SENT', 'Sent'), ('FINISHED', 'Finished')], default='CART', max_length=50),
        ),
    ]
