# Generated by Django 4.0.6 on 2022-08-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_alter_purchase_state_alter_rent_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='orders_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ID of order'),
        ),
    ]
