# Generated by Django 4.0.6 on 2022-08-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_purchase_orders_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total_orders_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total price of order'),
        ),
    ]
