# Generated by Django 4.0.6 on 2022-08-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_purchase_total_orders_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
