# Generated by Django 4.0.6 on 2022-08-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_alter_rent_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
