# Generated by Django 4.0.6 on 2022-08-24 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rent',
            table=None,
        ),
    ]
