# Generated by Django 4.0.6 on 2022-08-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_rent_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='address',
            field=models.CharField(default='12345', max_length=100, verbose_name='Address to delivery'),
        ),
        migrations.AddField(
            model_name='rent',
            name='city',
            field=models.CharField(default='12345', max_length=100, verbose_name='City to delivery'),
        ),
    ]
